FROM chainguard/python:latest-dev

WORKDIR /app
COPY backend/requirements.txt .
RUN python -m pip install -r requirements.txt

COPY backend/ .

EXPOSE 5000
CMD ["-m", "waitress", "--listen", "0.0.0.0:5000", "app:app"]