FROM chainguard/node:latest

WORKDIR /app

USER root

COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

RUN npm install -g serve@14
EXPOSE 3000

USER node

CMD ["./node_modules/serve/build/main.js", "./dist"]