[phases.setup]
aptPkgs = [ "...", "docker.io", "docker-compose", "python-distutils" ]

[phases.build]
cmds = [
  "docker-compose build --parallel"
]

[start]
cmd = "docker-compose up --build --remove-orphans"