[phases.setup]
aptPkgs = [ "...", "docker.io", "docker-compose", "docker-compose-plugin"]

[phases.build]
cmds = [
  "docker compose build"
]

[start]
cmd = "docker-compose up --build --remove-orphans"